# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bus_operator
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

    #Jpa configuration
  jpa:
    hibernate:
      ddl-auto: update  # Set to "create" for development, "update" for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  application:
    name: BUS-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8081

